### ISSUE TITLE
判断识别结束

### ISSUE THREAD

**Issue by springjphoenix** [zphhhhh/react-native-speech-iflytek#12]
如何判断识别结束呢？在onRecognizerResult函数中判断Recognizer.isListening()，不管结果为是或否，都会执行很多遍

**Comment by zphhhhh** [comment]
在 https://github.com/zphhhhh/react-native-speech-iflytek#events
```
onRecognizerResult(JSON result)
```
这里的 `result` 是一个 `JSON` 类型，含有字段 `isLast`：是否是最后一次识别，调用 Recognizer.stop() 后，isLast 值为 true，否则一直为 false
