### ISSUE TITLE
希望能对应更新一下1.X版本

### ISSUE THREAD

**Issue by Sunjiawei58** [zphhhhh/react-native-speech-iflytek#13]
看了一下1.3版本。没有支持对error的错误。2.0以上版本有对应的支持，但是只能支持React 0.47以上的版本。希望能更新出一版1.4版本，感激不尽

**Comment by zphhhhh** [comment]
已更新 v0.1.4: https://github.com/zphhhhh/react-native-speech-iflytek/tree/v0.1
