### ISSUE TITLE
iOS iflyMSC not found 

### ISSUE THREAD

**Issue by Sunjiawei58** [zphhhhh/react-native-speech-iflytek#15]
I tried the iOS version today and followed the tutorial on website putting the iflyMSC framework into the iOS project root folder, set the framework search path to $(PROJECT_DIR) . But still get this error, I don't really get what happened here. Can you give me some advice on that ?

![Uploading Screen Shot 2018-01-13 at 8.41.29 AM.png…]()

**Comment by zphhhhh** [comment]
这可能是 Xcode 的 bug，你在拖入 iflytek 时选择了 Copy items if needed 吗？没有选择就可能出现这种问题。建议删掉工程中的 iflytek，重新拖入。

**Comment by Sunjiawei58** [comment]
@zphhhhh 我这样尝试过几次啦。拖入的时候选择了copy items if needed。 但还是出现这样的问题，奇怪的是example就可以跑，不知道为什么会出现这样的情况。如果在framework 里面删掉iflytekMSC的话别的是可以编译通过直接运行的，您说的删除工程中的iflytek是指在framwork中删掉吗？

**Comment by zphhhhh** [comment]
在左侧 Framework 删除 iflytek.framework，另外要确保工程配置中 `General` > `Linked Frameworks and Libraries` 里也没有 iflytek.framework 了才行，你再试试？新版 Xcode 经常会找不到第三方的库...

**Comment by Sunjiawei58** [comment]
@zphhhhh 我这样又试了几遍还是出现找不到这个库的问题……网上说的删掉再添加，或者改building setting里面的framework search path 我都试了，结果都是一样。。另外我图好像上传不上去，内容就是报这个iflyMSC framework not found 的截图

**Comment by zphhhhh** [comment]
有没有尝试重新建项目？`react-native init AswsomeProject`，你可以把过程描述清除一下。我这边是做过测试的没有问题。

**Comment by Sunjiawei58** [comment]
@zphhhhh 我试试现在重新建一个项目看看，话说可以有别的联系方式吗？比如qq或者微信什么的，方便向您问问题呀？

**Comment by zphhhhh** [comment]
qq 313662349，不过有问题尽量提 issue 吧，因为可能其他人也有遇到同样问题的。另外问题解决了？

**Comment by Sunjiawei58** [comment]
@zphhhhh 问题解决啦！最后是在build setting里面的framework search path 不仅需要$(project_DIR) 还需要配置 $(inherited)这样就能找到framework啦
