### ISSUE TITLE
打release包会出错误

### ISSUE THREAD

**Issue by han4wluc** [zphhhhh/react-native-speech-iflytek#19]
开发debug版一切正常。

但是想打release包的时候会出以下错误。

```
no such file or directory: 'xxxx/Xcode/DerivedData/xxxx-hdbzzyndzuhubadplllkbkpmevbu/Build/Products/Release-iphonesimulator/libRNSpeechIFlytek.a'
```

**Comment by zphhhhh** [comment]
v1.0.1 已修复。
---
解决方法：将 RNSpeechIFlytek 设置为 Release 模式并单独 build 一次。
详细步骤：
1. change scheme from yourproject to  RNSpeechIFlytek
2. edit RNSpeechIFlytek's scheme, and change `Build Configuration` from `debug ` to `release`
3. build for RNSpeechIFlytek
4. change scheme back to yourproject
5. build and run

**Comment by zhonglaoban** [comment]
build faild for RNSpeechIFlytek in release mode

**Comment by zhonglaoban** [comment]
this solution is useless for archive

**Comment by zhonggithub** [comment]
archive模式的这个问题解决了吗
