### ISSUE TITLE
错误码10407

### ISSUE THREAD

**Issue by zhonggithub** [zphhhhh/react-native-speech-iflytek#29]
我按照readme 的步骤，在安卓端总是提示 用户校验失败，错误码10407，请问是否需要其他配置？

**Comment by zphhhhh** [comment]
用户校验失败是指 SDK 包和在讯飞开发者申请的 id 不一致，有替换自己申请的 id 对应的 SDK 包吗？

**Comment by zhonggithub** [comment]
替换了。按照readme 的步骤做的。方便加qq 或 微信 交流下吗

**Comment by zhonggithub** [comment]
问题已经解决了，sdk 替换出了问题，谢谢
