### ISSUE TITLE
调试没问题,但是打包报错

### ISSUE THREAD

**Issue by mike8625** [zphhhhh/react-native-speech-iflytek#47]
What went wrong:
Execution failed for task ':react-native-speech-iflytek:verifyReleaseResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  error: resource android:style/TextAppearance.Material.Widget.Button.Borderless.Colored not found.
  error: resource android:style/TextAppearance.Material.Widget.Button.Colored not found

---------------------------
    "react": "16.8.3",
    "react-native": "0.59.8",

**Comment by mike8625** [comment]
I have solve this issue. if somenoe find the same problem, please msg me.

**Comment by Jinzm** [comment]
我这里也出现了这样的问题。调试状态下正常，但是打包的时候出现了这个问题

**Comment by Jinzm** [comment]
> I have solve this issue. if somenoe find the same problem, please msg me.

你的修改方式是改的react-native-speech-iflytek里面的build.gradle吗？我按照控制台的提示修改之后就可以了，你也是这种修复方式吗

**Comment by zhonggithub** [comment]
怎么改的？我的控制台 没有任何信息提示呀

![image](https://user-images.githubusercontent.com/17545551/68932443-a10e9900-07cd-11ea-8b45-ba71eeb5ae2c.png)
