### ISSUE TITLE
加载不了该API

### ISSUE THREAD

**Issue by Sunjiawei58** [zphhhhh/react-native-speech-iflytek#5]
我尝试使用一个新的react native项目，npm install 之后，更换了libs，没有使用link，app能运行，但是会显示找不到合成和识别的init方法，link之后app就完全跑不起来了，一直报错，也没找到好的解决办法，

之前也尝试了先install，再link，再更换libs文件，但是完全按照example里面的文件写了之后
![image](https://user-images.githubusercontent.com/13588480/28230474-cef51bd6-68ac-11e7-9725-3f45ae85e1d8.png) 还是有这种错误，网上也没找到相关的解决方法，有什么建议吗？

**Comment by zphhhhh** [comment]
请确认在 `react-native init your-project` 之后可以正常运行，再安装语音包，可参照 Example 示例。

**Comment by Sunjiawei58** [comment]
谢谢！后来多试了几次安装成功加载了，有个问题想问题下，在recoginzer.OnVolumeChanged()这个函数中可以获得当前的Volume值以便进行判断吗？或者说有没有什么设置是可以设置这个函数的阈值的？我看了讯飞的文档，貌似没有找到这个说明。

**Comment by zphhhhh** [comment]
在事件处理中：https://github.com/zphhhhh/react-native-speech-iflytek#events 
- `onRecognizerVolumeChanged(Int volume)`
语音识别的音量大小，当识别的语音改变音量时会触发该事件

这个事件可以判断音量改变，但是无法主动设置音量阈值大小，这也是受限于讯飞官方不支持。

**Comment by Sunjiawei58** [comment]
好的，谢谢！那如果我想使用setParam()这个函数，里面会用到SpeechConst，在js里面能这样直接引用吗？

**Comment by zphhhhh** [comment]
你是指 `setParameter` 这个函数吧，可以使用下面的 `SpeechConst`
```
PARAM
ENGINE_TYPE
RESULT_TYPE
LANGUAGE
ACCENT
VAD_BOS
VAD_EOS
ASR_PTT
ASR_PTT
AUDIO_FORMAT
ASR_AUDIO_PATH
```
使用方法（与讯飞官方文档保持一致）：
```
Recognizer.setParameter(Recognizer.VAD_BOS, 'Your param')
```
需要注意的是，不是 `SpeechConst.VAD_BOS`  而是 `Recognizer.VAD_BOS`，我会在近期完善文档，谢谢关注！

**Comment by Sunjiawei58** [comment]
太感谢啦！今天在之前尝试的时候尝试过SpeechConst，发现用不了，就翻了一下Java代码找到了原字符串……以后用Recoginzer就好用多啦！
Ps：确实是在海外……最近刚上手讯飞的react native接口，这几天问题有点多还是多谢啦！

**Comment by zphhhhh** [comment]
有问题欢迎随时 issue，我会尽快回复。
