### ISSUE TITLE
很多次在Reload JS之后语音识别服务会卡住

### ISSUE THREAD

**Issue by Sunjiawei58** [zphhhhh/react-native-speech-iflytek#6]
最近在测试的发现，如果我修改了JS想Reload看效果的时候，有时会出现 语音合成之后一直在等待回调OnResult但是一直没有回应。但是在后台把程序关掉之后再进去就可以了。想问问这个会影响到实际产品发布吗？或者说有没有什么解决办法呢？

**Comment by Sunjiawei58** [comment]
我改成了这样：
 private void onIatError(SpeechError error) {
        WritableMap params = Arguments.createMap();
        params.putString("text",error.toString());
        params.putInt("errorCode",error.getErrorCode());
        this.onJSEvent(getReactApplicationContext(),"onRecognizerError",params);
        showTip(error.getPlainDescription(true));
    }

**Comment by zphhhhh** [comment]
> Reload看效果的时候，有时会出现 语音合成之后一直在等待回调
这是讯飞的原因，不会影响产品发布。
