### ISSUE TITLE
是否可以添加OnLatError的接口？

### ISSUE THREAD

**Issue by Sunjiawei58** [zphhhhh/react-native-speech-iflytek#7]
在测试中经常出现开始录入的时候没有人说话，然后就提示“您好像没有说话哦”，但是在自己的程序中没办法catch到这个error，可否在module中添加一个EventEmit把error分发到自定义函数中去呢？

**Comment by zphhhhh** [comment]
已经添加，我会在近期完善更多功能，谢谢关注！
